version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: indique
    ports:
      - "5432:5432"
volumes:
  pgdata: